server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: nba-service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # 连接超时时间
        readTimeout: 5000   # 读超时时间
        loggerLevel: full # 日志级别