server:
  port: 8081
  servlet:
    context-path: /

spring:
  application:
    name: nba-service-consumer

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full
ribbon:
  eager-load:
    clients: nba-service-provider
  eureka:
    enabled: true

nba-service-provider:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
    MaxAutoRetries: 1
    MaxAutoRetriesNextServer: 1
    OkToRetryOnAllOperations: true
    ServerListRefreshInterval: 2000
    ConnectTimeout: 3000
    ReadTimeout: 3000